spring:
  application:
    name: simple-service

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

keycloak:
  auth-server-url: http://192.168.99.100:8080/auth
  realm: realmtest
  resource: sampleClient
  principal-attribute: preferred_username
server:
  port: 9080

rest:
  security:
    cors:
      allowed-origins=*:rest.security.cors.allowed-origins=*
